{{- if .Values.keeper.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: keeper
  labels:
    app: keeper
    {{- include "optscale.labels" . | nindent 4 }}
spec:
  type: {{ .Values.keeper.service.type }}
  ports:
    - port: {{ .Values.keeper.service.port }}
      targetPort: {{ .Values.keeper.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: keeper
    {{- include "optscale.selectorLabels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keeper
  labels:
    app: keeper
    {{- include "optscale.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.keeper.replicaCount }}
  selector:
    matchLabels:
      app: keeper
      {{- include "optscale.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: keeper
        {{- include "optscale.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        {{- include "optscale.waitForService" (dict "name" "etcd" "service" "etcd" "namespace" .Release.Namespace "port" "2379") | nindent 8 }}
      containers:
        - name: keeper
          image: {{ include "optscale.image" (dict "global" .Values.global "image" .Values.keeper.image) }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.keeper.service.targetPort }}
              name: http
          env:
            {{- include "optscale.commonEnv" . | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "optscale.fullname" . }}-config
          {{- include "optscale.readinessProbe" (dict "port" .Values.keeper.service.targetPort) | nindent 10 }}
          {{- with .Values.keeper.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
