apiVersion: v1
kind: Secret
metadata:
  name: {{ include "optscale.fullname" . }}-cluster
  labels:
    {{- include "optscale.labels" . | nindent 4 }}
type: Opaque
stringData:
  cluster-secret: {{ .Values.secrets.clusterSecret | quote }}
  encryption-salt: {{ .Values.secrets.encryptionSalt | quote }}
  encryption-key: {{ .Values.secrets.encryptionKey | quote }}
---
{{- if .Values.mariadb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "optscale.fullname" . }}-mariadb
  labels:
    {{- include "optscale.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.mariadb.credentials.rootPassword | quote }}
{{- end }}
---
{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "optscale.fullname" . }}-mongodb
  labels:
    {{- include "optscale.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.mongodb.credentials.username | quote }}
  password: {{ .Values.mongodb.credentials.password | quote }}
  key: {{ .Values.mongodb.credentials.key | quote }}
{{- end }}
---
{{- if .Values.rabbitmq.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "optscale.fullname" . }}-rabbitmq
  labels:
    {{- include "optscale.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.rabbitmq.credentials.username | quote }}
  password: {{ .Values.rabbitmq.credentials.password | quote }}
  cookie: {{ .Values.rabbitmq.credentials.cookie | quote }}
{{- end }}
---
{{- if .Values.clickhouse.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "optscale.fullname" . }}-clickhouse
  labels:
    {{- include "optscale.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.clickhouse.db.password | quote }}
{{- end }}
---
{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "optscale.fullname" . }}-minio
  labels:
    {{- include "optscale.labels" . | nindent 4 }}
type: Opaque
stringData:
  access-key: {{ .Values.minio.credentials.accessKey | quote }}
  secret-key: {{ .Values.minio.credentials.secretKey | quote }}
{{- end }}
---
{{- if .Values.serviceCredentials.aws.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "optscale.fullname" . }}-aws-credentials
  labels:
    {{- include "optscale.labels" . | nindent 4 }}
type: Opaque
stringData:
  access-key-id: {{ .Values.serviceCredentials.aws.accessKeyId | quote }}
  secret-access-key: {{ .Values.serviceCredentials.aws.secretAccessKey | quote }}
{{- end }}
---
{{- if .Values.smtp.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "optscale.fullname" . }}-smtp
  labels:
    {{- include "optscale.labels" . | nindent 4 }}
type: Opaque
stringData:
  server: {{ .Values.smtp.server | quote }}
  port: {{ .Values.smtp.port | quote }}
  email: {{ .Values.smtp.email | quote }}
  login: {{ .Values.smtp.login | quote }}
  password: {{ .Values.smtp.password | quote }}
  protocol: {{ .Values.smtp.protocol | quote }}
{{- end }}
